import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: '',
    title: '-- Network Services',
    moduleName: '',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/dashboard/main',
    title: 'Private Networks',
    moduleName: 'dashboard',
    iconType: 'material-icons-two-tone',
    icon: 'gps_not_fixed',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/dashboard/main',
    title: 'Load Balancing',
    moduleName: 'dashboard',
    iconType: 'material-icons-two-tone',
    icon: 'import_export',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '',
    title: '-- Compute Services',
    moduleName: '',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/dashboard/main',
    title: 'Elastic Compute',
    moduleName: 'dashboard',
    iconType: 'material-icons-two-tone',
    icon: 'memory',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },

  {
    path: '/dashboard/main',
    title: 'Containers',
    moduleName: 'dashboard',
    iconType: 'material-icons-two-tone',
    icon: 'grid_on',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/dashboard/main',
    title: 'Functions',
    moduleName: 'dashboard',
    iconType: 'material-icons-two-tone',
    icon: 'device_hub',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '',
    title: '-- Database Services',
    moduleName: '',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/dashboard/main',
    title: 'Relational Database',
    moduleName: 'dashboard',
    iconType: 'material-icons-two-tone',
    icon: 'dns',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/dashboard/main',
    title: 'Caching',
    moduleName: 'dashboard',
    iconType: 'material-icons-two-tone',
    icon: 'link',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/dashboard/main',
    title: 'Message Bus',
    moduleName: 'dashboard',
    iconType: 'material-icons-two-tone',
    icon: 'call_split',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  }, 
  {
    path: '',
    title: '-- Monitoring',
    moduleName: '',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/dashboard/main',
    title: 'Performance',
    moduleName: 'dashboard',
    iconType: 'material-icons-two-tone',
    icon: 'equalizer',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/dashboard/main',
    title: 'Alerting',
    moduleName: 'dashboard',
    iconType: 'material-icons-two-tone',
    icon: 'access_alarms',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '',
    title: '-- Configuration',
    moduleName: '',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/platforms',
    title: 'Platforms',
    moduleName: 'dashboard',
    iconType: 'material-icons-two-tone',
    icon: 'storage',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/identity',
    title: 'Identity Management',
    moduleName: 'Identity',
    iconType: 'material-icons-two-tone',
    icon: 'security',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/dashboard/main',
    title: 'Tagging',
    moduleName: 'dashboard',
    iconType: 'material-icons-two-tone',
    icon: 'assistant',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/dashboard/main',
    title: 'Credentials',
    moduleName: 'dashboard',
    iconType: 'material-icons-two-tone',
    icon: 'lock',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
];
