version: 0.2

phases:
    pre_build:
        commands:
        - echo Restore started on `date`
        - dotnet restore prinubes.sln
        - echo Logging in to Amazon ECR...
        - aws --version
        - $(aws ecr get-login --region us-east-1 --no-include-email)
        - REPOSITORY_URI=299129499635.dkr.ecr.us-east-1.amazonaws.com/development
        - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
        - IMAGE_TAG=${COMMIT_HASH:=latest}
    build:
        commands:
        - echo Build started on `date`
        - dotnet build -c release -o ./build_output prinubes.sln
        - echo Building the Docker images...
        - docker-compose -f docker-compose.yml build 
        - docker tag prinubes-platformworker:latest $REPOSITORY_URI/prinubes-platformworker:$IMAGE_TAG
        - docker tag prinubes-platform:latest $REPOSITORY_URI/prinubes-platform:$IMAGE_TAG
        - docker tag prinubes-identity:latest $REPOSITORY_URI/prinubes-identity:$IMAGE_TAG
    post_build:
        commands:
        - echo Build completed on `date`
        - echo Pushing the Docker images...
        - docker push $REPOSITORY_URI/prinubes-platformworker:$IMAGE_TAG
        - docker push $REPOSITORY_URI/prinubes-platform:$IMAGE_TAG
        - docker push $REPOSITORY_URI/prinubes-identity:$IMAGE_TAG
artifacts:
    files:
    - "**/*"
