version: '3.4'

services:
  Identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - JWT_SECRET=EBOHltOtlvsBorhGvfOxq27k5X334nYU
      - JWT_EXPIRE_TIME=100
      - MYSQL_SERVER=10.0.1.23
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=prinubes_identity_production
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1qazxsw2
      - REDIS_CACHE_HOST=10.0.1.28
      - REDIS_CACHE_PORT=6379
      - REDIS_CACHE_PASSWORD=
      - REDIS_TTL=30
      - KAFKA_BOOTSTRAP=10.0.1.24
      - KAFKA_IDEMPOTENCE=true
      - KAFKA_RETRIES=20
      - KAFKA_CONSUMER_GROUP_ID=identity
      - KAFKA_ENABLE_AUTO_COMMIT=false
    ports:
      - "7001:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
  Platform:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - JWT_SECRET=EBOHltOtlvsBorhGvfOxq27k5X334nYU
      - JWT_EXPIRE_TIME=100
      - MYSQL_SERVER=10.0.1.23
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=prinubes_platform_production
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1qazxsw2
      - REDIS_CACHE_HOST=10.0.1.28
      - REDIS_CACHE_PORT=6379
      - REDIS_CACHE_PASSWORD=
      - REDIS_TTL=30
      - KAFKA_BOOTSTRAP=10.0.1.24
      - KAFKA_IDEMPOTENCE=true
      - KAFKA_RETRIES=20
      - KAFKA_CONSUMER_GROUP_ID=platform
      - KAFKA_ENABLE_AUTO_COMMIT=false
    ports:
      - "7002:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
  PlatformWorker:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - JWT_SECRET=EBOHltOtlvsBorhGvfOxq27k5X334nYU
      - JWT_EXPIRE_TIME=100
      - MYSQL_SERVER=10.0.1.23
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=prinubes_platformworker_production
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1qazxsw2
      - REDIS_CACHE_HOST=10.0.1.28
      - REDIS_CACHE_PORT=6379
      - REDIS_CACHE_PASSWORD=
      - REDIS_TTL=30
      - KAFKA_BOOTSTRAP=10.0.1.24
      - KAFKA_IDEMPOTENCE=true
      - KAFKA_RETRIES=20
      - KAFKA_CONSUMER_GROUP_ID=platformworker
      - KAFKA_ENABLE_AUTO_COMMIT=false
    ports:
      - "7003:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
