version: '3.4'

services:
  Identity:
    image: prinubes-identity
    build:
      context: .
      dockerfile: Identity/Dockerfile
  Platform:
    image: prinubes-platform
    build:
      context: .
      dockerfile: Platform/Dockerfile
  PlatformWorker:
    image: prinubes-platformworker
    build:
      context: .
      dockerfile: PlatformWorker/Dockerfile
