/**
 * IdentityMicroservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupDatabaseModel } from './groupDatabaseModel';


export interface OrganizationDatabaseModel { 
    organization?: string | null;
    groups?: Array<GroupDatabaseModel> | null;
    id: string;
    create_timestamp?: string;
    update_timestamp?: string;
    row_version?: string | null;
}

