/**
 * IdentityMicroservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrganizationDatabaseModel } from './organizationDatabaseModel';


export interface TaggingDatabaseModel { 
    organization_id?: string;
    organization?: OrganizationDatabaseModel;
    key?: string | null;
    value?: string | null;
    id: string;
    create_timestamp?: string;
    update_timestamp?: string;
    row_version?: string | null;
}

