/**
 * IdentityMicroservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type UserRole = 'Dummy' | 'User' | 'Developer' | 'Administrator' | 'EnterpriseAdministrator';

export const UserRole = {
    Dummy: 'Dummy' as UserRole,
    User: 'User' as UserRole,
    Developer: 'Developer' as UserRole,
    Administrator: 'Administrator' as UserRole,
    EnterpriseAdministrator: 'EnterpriseAdministrator' as UserRole
};

