/**
 * IdentityMicroservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRole } from './userRole';
import { GroupDatabaseModel } from './groupDatabaseModel';


export interface UserDatabaseModel { 
    password_hash?: string | null;
    password_salt?: string | null;
    email_address?: string | null;
    firstname?: string | null;
    lastname?: string | null;
    groups?: Array<GroupDatabaseModel> | null;
    role?: UserRole;
    id: string;
    create_timestamp?: string;
    update_timestamp?: string;
    row_version?: string | null;
}

