apiVersion: v1
kind: PersistentVolume
metadata:
  name: organizations-mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: organizations-mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
kind: Service
apiVersion: v1
metadata:
  name: organizations-mysql-service
spec:
  selector:
    app: organizations-mysql
  ports:
  - protocol: TCP
    port: 3306
    nodePort: 32321
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: organizations-mysql-deployment
spec:
  selector:
    matchLabels:
      app: organizations-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: organizations-mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: VMware1!
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: organizations-mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: organizations-mysql-persistent-storage
        persistentVolumeClaim:
          claimName: organizations-mysql-pv-claim